apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname-user-msi
  namespace: nexabank
spec:
  provider: azure
  secretObjects:
  - secretName: nexa-secrets
    type: Opaque
    data: 
    - objectName: DB-PASSWORD
      key: DB_PASSWORD
    - objectName: JWT-SECRET
      key: JWT_SECRET
    - objectName: AZURE-STORAGE-CONNECTION-STRING
      key: AZURE_STORAGE_CONNECTION_STRING
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: ""
    keyvaultName: "apexbank-keyvault"
    objects: |
      array:
        - |
          objectName: DB-PASSWORD
          objectType: secret
          objectVersion: ""
        - |
          objectName: JWT-SECRET
          objectType: secret
          objectVersion: ""
        - |
          objectName: AZURE-STORAGE-CONNECTION-STRING
          objectType: secret
          objectVersion: ""
    tenantId: "d7c02441-9846-4741-b172-a549e250b870"
