apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nexa-ingress
  namespace: nexabank
spec:
  ingressClassName: azure-application-gateway
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nexa-api-gateway
            port:
              number: 80