# ============================================================
# User Service — Deployment + ClusterIP Service (INTERNAL)
# ============================================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexa-user
  namespace: nexabank
  labels:
    app: nexa-user
    component: user
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nexa-user
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: nexa-user
        component: user
    spec:
      containers:
        - name: user
          image: nexabankacr.azurecr.io/nexa-user:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3002
          envFrom:
            - configMapRef:
                name: nexa-config
          env:
            - name: PORT
              value: "3002"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nexa-secrets
                  key: DB_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: nexa-secrets
                  key: JWT_SECRET
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          volumeMounts:
            - name: secrets-store-inline
              mountPath: "/mnt/secrets-store"
              readOnly: true
          livenessProbe:
            httpGet:
              path: /health
              port: 3002
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /health
              port: 3002
            initialDelaySeconds: 10
            periodSeconds: 10
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "azure-kvname-user-msi"
---
apiVersion: v1
kind: Service
metadata:
  name: nexa-user
  namespace: nexabank
  labels:
    app: nexa-user
spec:
  type: ClusterIP
  selector:
    app: nexa-user
  ports:
    - name: http
      port: 3002
      targetPort: 3002
      protocol: TCP

